
spring:
  thymeleaf:
    cache: false
  template:
    cache: false


  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:h2:file:~/tomato-dev;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: threaddump, heapdump
  metrics:
    export:
      atlas:
        enabled: false


