server:
  port: 9002

  
logging:
  level:
    org.springframework.cloud: 'DEBUG'

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        #git:
        #  uri: https://github.com/walterfan/helloworld
  profiles:
    active: native

