# refer to https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/common-application-properties.html
spring:
  profiles:
  #use dev environment by default
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
---
# dev environment
spring:
  profiles: dev
  redis:
    host: localhost
    port: 6379
server:
  port: 8000

---
# production environment
spring:
  profiles: pro
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8080